### ISSUE TITLE
Actualizar función $tsCore->setJSON()

### ISSUE THREAD

**Issue by ghost** [isidromlc/PHPost#8]
Sería bueno actualizar la librería JSON por la que viene por defecto en PHP.
Por lo general, los hostings de ahora traen PHP 5.4, así que no sería un problema ya que [estas funciones](https://www.php.net/manual/es/ref.json.php) fueron introducidas en la versión 5.2.0 de PHP.

Referencia: https://github.com/isidromlc/PHPost/blob/master/inc/class/c.core.php#L189

**Comment by joelmiguelvalente** [comment]
```
/*
		setJSON($tsContent)
	*/
	function setJSON($data, $type = 'encode'){
      if($type == 'encode') return json_encode($data);
      elseif($type == 'decode') return json_decode($data);            
	}
```
